### ISSUE TITLE
[node/js] Doc not syncing

### ISSUE THREAD

**Issue by mattdesl** [n0-computer/iroh-ffi#109]
I'm trying a basic doc sync test, code here:

https://gist.github.com/mattdesl/efdedcf47494a24946273d3b01d2fd79

`server.js` opens a node from a local tmp dir and subscribes for doc changes
`peer.js` runs a new tmp node that changes the `"foo"` key to a random value

If I close the server, I can re-open it but it will not behave correctly anymore.

Steps to Bug:

1. Run `node src/server.js` in terminal
2. Once its running, close the terminal process with Cmd + C
3. Then run it again, `node src/server.js` and copy the ticket
4. Now in another terminal, run `node src/peer.js [copied_ticket]`

The server will not print any doc changes. However, if you remove the data dir `rm -rf tmp/` and redo the steps without step 2 (exiting process), each time you run the peer script it will print doc events in the server. It is just that closing and re-opening the server seems to be the issue.

Another more general issue I have with this, how can a remote node wait for the 'content ready' event on other nodes? Right now I have a delay of 5 seconds which feels like a hack. I'd rather wait until I know the content has been synced, and then close.

**Comment by ramfox** [comment]
Hi! I mentioned in https://github.com/n0-computer/iroh-ffi/issues/108#issuecomment-1986419297 that we are not going to be supporting node-js in ffi, since the apis have such wildly different expectations in the two languages.

But to just maybe give a tiny bit of closure, lmao. We are likely not cleaning up resources correctly when the node shuts down, and we are likely not reporting the errors correctly when they happen on the rust side of the ffi barrier. So when you go to start the node again, there may be weird socket or node_id things happening, which prevent the `src/peer.js` side from connecting correctly. Not totally sure.

As for the second issue, documents aren't designed to notify you if a peer has finished downloading specific content, only that both peers in a sync have the "same view of the world" (`LiveEvent::SyncFinished`).  And doing a "sync" is actually a different step than sending over the content itself. You can wait for a `LiveEvent::NeighborDown` event to see if the peer has disconnected?

If you are looking for data transfer, the `blobs` API is the better one to look at. `IrohNode.blobsAddFromPath` or `IrohNode.blobsAddBytes` to add the bytes and `IrohNode.blobsDownload` to receive them. The ffi apis don't include tickets for blobs in this iteration, though, so you would need to pass in the addresses, derp url, and hash in separately.
